-- TRSDB.MV_TRS_TB_ACTUAL_ACCOUNT_AMOUNT source

CREATE MATERIALIZED VIEW "MV_TRS_TB_ACTUAL_ACCOUNT_AMOUNT" ("ENTITY_CODE", "CURRENT_CODE", "ENTITY_ID", "COMPANY_ID", "COUNTRY_ID", "SALES_FUNCTION_ID", "PERIOD", "MONTH", "T1_CODE", "T1_NAME", "T2_CODE", "T2_NAME", "T2_DEBIT_CREDIT", "T3_CODE", "T3_NAME", "T3_DEBIT_CREDIT", "T4_CODE", "T4_NAME", "T4_DEBIT_CREDIT", "T5_CODE", "T5_NAME", "T5_DEBIT_CREDIT", "T6_CODE", "T6_NAME", "T6_DEBIT_CREDIT", "T7_CODE", "T7_NAME", "T7_DEBIT_CREDIT", "ACCUMULATED_AMOUNT", "CURRENT_AMOUNT", "ACCUMULATED_AMOUNT_ORI", "CURRENT_AMOUNT_ORI", "CURRENCY_CODE", "IFRS_VERSION", "SCENARIO", "LANGUAGE", "MV_UPDATED_TIME")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (sysdate +30/1440)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS WITH TABLE1 AS (
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T7_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T6_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T5_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T4_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T3_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T2_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
UNION ALL
SELECT 
t1.entity_code,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
t1.ACCUMULATED_AMOUNT ,
t1.current_amount,
t1.CURRENCY_CODE,
t2.ifrs_version,
t1.SCENARIO,
LANGUAGE
FROM TRS_FACT_TRIAL_BALANCE t1
JOIN V_TRS_DIM_ACCOUNTING_RANKING t2 ON t1.account_code = t2.T1_CODE AND t1.IFRS_VERSION = t2.IFRS_VERSION 
WHERE t1.VALUE_TYPE = 'actual'
)
SELECT 
t1.entity_code,
t3.current_code,
t2.entity_id,
t2.company_id,
t2.country_id,
t2.sales_function_id,
t1.period,
t1.MONTH,
T1_CODE,
T1_NAME,
T2_CODE,
T2_NAME,
T2_DEBIT_CREDIT,
T3_CODE,
T3_NAME,
T3_DEBIT_CREDIT,
T4_CODE,
T4_NAME,
T4_DEBIT_CREDIT,
T5_CODE,
T5_NAME,
T5_DEBIT_CREDIT,
T6_CODE,
T6_NAME,
T6_DEBIT_CREDIT,
T7_CODE,
T7_NAME,
T7_DEBIT_CREDIT,
CASE WHEN t1.T2_DEBIT_CREDIT ='C' THEN t1.ACCUMULATED_AMOUNT*(-1) 
  WHEN t1.T2_DEBIT_CREDIT !='C' THEN t1.ACCUMULATED_AMOUNT
  END AS ACCUMULATED_AMOUNT,
CASE WHEN t1.T2_DEBIT_CREDIT ='C' THEN t1.current_amount*(-1) 
  WHEN t1.T2_DEBIT_CREDIT !='C' THEN t1.current_amount
  END AS CURRENT_AMOUNT,
t1.ACCUMULATED_AMOUNT AS ACCUMULATED_AMOUNT_ORI,
t1.CURRENT_AMOUNT AS CURRENT_AMOUNT_ORI,
t1.CURRENCY_CODE,
t1.ifrs_version,
t1.SCENARIO,
t1.LANGUAGE,
SYSDATE AS MV_UPDATED_TIME
FROM TABLE1 t1
LEFT JOIN V_TRS_DIM_ENTITY t2 ON t1.ENTITY_CODE =t2.entity_code AND t1.LANGUAGE = t2.LANGUAGE
LEFT JOIN V_TRS_DIM_ENTITY_CUR t3 ON t1.ENTITY_CODE = T3.ENTITY_CODE 
;

COMMENT ON MATERIALIZED VIEW TRSDB.MV_TRS_TB_ACTUAL_ACCOUNT_AMOUNT IS 'snapshot table for snapshot TRSDB.MV_TRS_TB_ACTUAL_ACCOUNT_AMOUNT';