-- TRSDB.TRS_FACT_CFC_RECOGNIZED_LOSS definition

CREATE TABLE "TRSDB"."TRS_FACT_CFC_RECOGNIZED_LOSS" 
   (    "ID" VARCHAR2(36) NOT NULL ENABLE, 
    "CFC_ENTITY_CODE" VARCHAR2(255) NOT NULL ENABLE, 
    "SCENARIO" VARCHAR2(255) NOT NULL ENABLE, 
    "TYPE" VARCHAR2(255) NOT NULL ENABLE, 
    "DECLARE_DATE" DATE NOT NULL ENABLE, 
    "REC_YEAR" VARCHAR2(255) NOT NULL ENABLE, 
    "CREATED_BY" VARCHAR2(255), 
    "CREATED_TIME" DATE, 
    "UPDATED_BY" VARCHAR2(255), 
    "UPDATED_TIME" DATE, 
    "REDUC_RATIO" NUMBER(24,17), 
    "AMOUNT" NUMBER(24,5), 
    "DOCUMENT_DATE" DATE,
    "DOCUMENT_CURRENCY_ID" VARCHAR2(255),
    "EXCHANGE_RATE_DOCUMENT" NUMBER(24,5),
    "DOCUMENT_AMOUNT" NUMBER(24,5),
     PRIMARY KEY ("CFC_ENTITY_CODE","SCENARIO","TYPE","DECLARE_DATE","REC_YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
