-- TRSDB.V_TRS_FACT_CFC_RECOGNIZED_LOSS source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TRSDB"."V_TRS_FACT_CFC_RECOGNIZED_LOSS" ("ID", "PERIOD", "CFC_ENTITY_CODE", "SCENARIO", "TYPE", "DECLARE_DATE", "REC_YEAR", "CURRENCY", "REDUC_RATIO", "AMOUNT_ORI", "EXCHANGE_RATIO", "AMOUNT","DOCUMENT_DATE", "DOCUMENT_CURRENCY_ID", "EXCHANGE_RATE_DOCUMENT", "DOCUMENT_AMOUNT") AS 
  WITH CTE_PERIOD AS (
SELECT
    PERIOD,
    SCENARIO,
    ENTITY_CODE
FROM V_TRS_FACT_CFC_ENTITY_VERSION
),RECOGNIZED_LOSS AS(
SELECT
t1.ID,
t2.CURRENT_CODE AS CFC_ENTITY_CODE, --用CURRENT_CODE輸出
t1.SCENARIO ,
t1."TYPE" ,
t1.DECLARE_DATE ,
t1.REC_YEAR ,
t1.REDUC_RATIO ,
t1.AMOUNT ,
t2.country_id,
t1.DOCUMENT_DATE,  
t1.DOCUMENT_CURRENCY_ID,  
t1.EXCHANGE_RATE_DOCUMENT,  
t1.DOCUMENT_AMOUNT
FROM TRS_FACT_CFC_RECOGNIZED_LOSS t1
LEFT JOIN V_TRS_DIM_ENTITY_CUR  t2 ON t1.CFC_ENTITY_CODE = t2.ENTITY_CODE 
)
SELECT
t1.ID,
t0.PERIOD,
t1.CFC_ENTITY_CODE,
t1.scenario,
t1.type,
t1.DECLARE_DATE,
t1.REC_YEAR,
t3.CURRENCY_ID as CURRENCY,
t1.REDUC_RATIO,
t1.AMOUNT as AMOUNT_ORI,
t4.AVG_EXCHANGE_RATIO as EXCHANGE_RATIO,
t4.AVG_EXCHANGE_RATIO * nvl(t1.AMOUNT,0) as AMOUNT,
t1.DOCUMENT_DATE,  
t1.DOCUMENT_CURRENCY_ID,  
t1.EXCHANGE_RATE_DOCUMENT,  
t1.DOCUMENT_AMOUNT
FROM CTE_PERIOD t0
JOIN RECOGNIZED_LOSS t1 ON t1.DECLARE_DATE BETWEEN TRUNC(t0.PERIOD, 'YEAR') AND t0.PERIOD AND t0.ENTITY_CODE = t1.CFC_ENTITY_CODE AND t0.SCENARIO = t1.SCENARIO
LEFT JOIN (SELECT DISTINCT ENTITY_CODE,CURRENCY_ID FROM V_TRS_DIM_ENTITY) t3 on t1.CFC_ENTITY_CODE = t3.ENTITY_CODE 
left join V_TRS_FACT_EXCHANGE_BANKOFTW t4 on t3.CURRENCY_ID = t4.CURRENCY_ID and t1.scenario = t4.scenario AND t4.TARGET_CURRENCY_ID = 'NTD' AND TO_CHAR(t0.PERIOD, 'YYYY-MM') = t4.PERIOD
;
