SELECT 
DISTINCT
T1.PERIOD,
T2.current_code,
T3.ENTITY_NAME
FROM 
[dbo].[TRS_FACT_COUNTRY_REPORT] T1
LEFT JOIN
TRSDB.dbo.V_TRS_DIM_ENTITY_CUR T2
ON T1.ENTITY_ID = T2.ENTITY_CODE
LEFT JOIN 
V_TRS_DIM_ENTITY T3
ON T2.ENTITY_CODE = T3.ENTITY_ID
LEFT JOIN 
V_TRS_DIM_COUNTRY T4
ON T3.COUNTRY_ID = T4.COUNTRY_ID
WHERE T3.FR_LOCALE='${fr_locale}'