SELECT '1' AS ID, 'col_pre_tax_income' AS TYPE
UNION ALL
SELECT '2' AS ID, 'col_tax_paid' AS TYPE
UNION ALL
SELECT '3' AS ID, 'col_accu_surplus' AS TYPE
UNION ALL
SELECT '4' AS ID, 'col_tangible_asset' AS TYPE
UNION ALL
SELECT '5' AS ID, 'col_income' AS TYPE
UNION ALL
SELECT '6' AS ID, 'col_num_of_emp' AS TYPE
UNION ALL
SELECT '7' AS ID, 'col_paid_up_capital' AS TYPE
UNION ALL
SELECT '8' AS ID, 'col_income_rel' AS TYPE
UNION ALL
SELECT '9' AS ID, 'col_curr_tax_payable' AS TYPE
UNION ALL
SELECT '10' AS ID, 'col_income_non_rel' AS TYPE